<div class="top-bar" id="dropdown-bar">
    <div class="top-bar-left">
        <nav class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="large" aria-label="<?php echo $this->translate('Mobile navigation'); ?>">
            <button class="menu-toggle" type="button" data-toggle="offCanvas" aria-label="<?php echo $this->translate('Menu'); ?>"><i class="fas fa-bars"></i></button>
        </nav>
        <?php $siteLogo = ($this->themeSetting('logo')) ? '<img src="' . $this->themeSettingAssetUrl('logo') . '" title="Logo" alt="">' : ''; ?>
        <h1 class="site-title"><a href="<?php echo $site->url(); ?>"><?php echo $siteLogo; ?><span class="site-title-label <?php echo ($siteLogo !== '') ? 'sr-only' : ''; ?>"><?php echo $this->escapeHtml($site->title()); ?></span></a></h1>
    </div>
    <nav class="top-bar-right" id="responsive-menu" aria-label="<?php echo $this->translate('Main'); ?>">
        <div class="flex-fix">
            <?php echo $site->publicNav()->menu()->setPartial('common/foundation-navigation.phtml')->renderPartialWithParams(['layout' => 'dropdown', 'navId' => 'main-nav']); ?>
        </div>
    </nav>
    <button type="button" class="search-toggle closed button" aria-controls="search-form" aria-expanded="false" aria-label="<?php echo $this->translate('Toggle search form'); ?>"><i class="fas fa-search"></i></button>
</div>
<div id="search-container" class="closed">
    <?php echo $this->partial('common/search-form'); ?>
</div>
