<?php if ($this->themeSetting('logo')): ?>
    <?php $titleLink = '<a href="' . $site->url() . '" class="site-title"><img src="' . $this->themeSettingAssetUrl('logo') . '" title="Logo"></a>'; ?>
<?php else: ?>
    <?php $titleLink = '<a href="' . $site->url() . '" class="site-title">' . $this->pageTitle($site->title()) . '</a>'; ?>
<?php endif; ?>
<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="large">
    <button class="menu-toggle" type="button" data-toggle="offCanvas" aria-label="<?php echo $this->translate('Menu'); ?>"><i class="fas fa-bars"></i></button>
    <?php echo $titleLink; ?>
</div>
<div class="desktop">
  <?php echo $titleLink; ?>
  <?php echo $site->publicNav()->menu()->setPartial('common/foundation-navigation.phtml')->renderPartialWithParams(['layout' => 'vertical']); ?>
  <div class="search">
      <?php echo $this->partial('common/search-form'); ?>
  </div>
</div>
