<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
$filterLocale = $this->themeSetting('filter_locale_values');
$showLocale = $this->themeSetting('show_locale_label');
$lang = $this->lang();
$headingTerm = $this->siteSetting('browse_heading_property_term');
?>
<dl>
<?php foreach ($values as $term => $propertyData): ?>
    <div class="property">
        <dt>
        <?php if ($propertyData['alternate_label']): ?>
        <?php echo $escape($propertyData['alternate_label']); ?>
        <?php else: ?>
        <?php echo $escape($translate($propertyData['property']->label())); ?>
        <?php endif; ?>
        <?php if ('term' === $labelInfo): ?>
        <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
        <?php elseif ('vocab' === $labelInfo): ?>
        <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
        <?php endif; ?>
        </dt>
        <div class="values">
        <?php foreach ($propertyData['values'] as $value): ?>
            <?php
            $valueType = $value->type();
            $valueLang = $value->lang();
            $class = ['value'];
            if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
                $class[] = 'resource';
                $class[] = $escape($value->valueResource()->resourceName());
            } elseif ('uri' == $valueType) {
                $class[] = 'uri';
            }
            if (!$value->isPublic()) {
                $class[] = 'private';
            }
            ?>
            <?php if (($filterLocale == 0) || ($valueLang == '') || ($valueLang == $lang)): ?>
            <dl class="<?php echo implode(' ', $class); ?>" lang="<?php echo $escape($valueLang); ?>">
                <?php if (($showLocale == 1) && ($valueLang)): ?>
                <span class="language"><?php echo $valueLang; ?></span>
                <?php endif; ?>

				<?php if ($linkedResource = $value->valueResource()):?>
					<?php

                    $linkedResourceTitle = null;

                    if ($headingTerm) {
                        if (! ($linkedResourceTitle = $linkedResource->value($headingTerm, [
                            'lang' => $lang
                        ]))) {
                            $linkedResourceTitle = $linkedResource->value($headingTerm, [
                                'default' => $translate('[Untitled]')
                            ]);
                        }
                    } else {
                        $template = $linkedResource->resourceTemplate();
                        if ($template && $template->titleProperty()) {
                            if (($filterLocale == 0) || ! ($linkedResourceTitle = $linkedResource->value($template->titleProperty()
                                ->term(), [
                                'lang' => $lang
                            ]))) {
                                $linkedResourceTitle = $linkedResource->value($template->titleProperty()
                                    ->term());
                            }
                        }
                    }
                    if (! $linkedResourceTitle) {
                        $linkedResourceTitle = $linkedResource->displayTitle();
                    }

                    $linkContent = $this->thumbnail($value->valueResource(), 'square') . '<span class="resource-name">' . $escape($linkedResourceTitle) . "</span>";
                    echo $value->valueResource()->linkRaw($linkContent, null, [
                        'class' => 'resource-link'
                    ]);
                    ?>
				<?php else: ?>
					<?php echo $value->asHtml(); ?>
                <?php endif;?>
            </dl>
            <?php endif; ?>
        <?php endforeach; ?>
        </div>
    </div>
<?php endforeach; ?>
</dl>