<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->headScript()->appendFile($this->assetUrl('js/browse.js'));
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');

$query = $this->params()->fromQuery();
$itemSetShow = isset($itemSet);
if ($itemSetShow):
    $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id();
endif;

$layoutSetting = $this->themeSetting('browse_layout');
$gridState = ($layoutSetting == 'togglegrid') ? 'disabled' : '';
$listState = ($layoutSetting == 'togglelist') ? 'disabled': '';
$isGrid = (!isset($layoutSetting) || strpos($layoutSetting, 'grid') !== false) ? true : false;
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
$bodyTruncate = $this->themeSetting('truncate_body_property');

$sortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title'
    ],
    [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => $translate('Class'),
        'value' => 'resource_class_label'
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created'
    ],
];

$filterLocale = $this->themeSetting('filter_locale_values');
$lang = $this->lang();
?>

<?php if ($itemSetShow): ?>
	<?php
	if ($headingTerm) {
	    if (!($itemSetTitle = $itemSet->value($headingTerm, ['lang' => $lang]))) {
	        $itemSetTitle = $itemSet->value($headingTerm, ['default' => $translate('[Untitled]')]);
	    }
	} else {
	    $template = $itemSet->resourceTemplate();
	    if ($template && $template->titleProperty()) {
	        if (($filterLocale == 0) || !($itemSetTitle = $itemSet->value($template->titleProperty()->term(), ['lang' => $lang]))) {
	            $itemSetTitle = $itemSet->value($template->titleProperty()->term());
	        }
	    }
	}
	if (!$itemSetTitle) {
	    $itemSetTitle = $itemSet->displayTitle();
	}
    echo $this->pageTitle($itemSetTitle, 2);
    ?>
    <h3><?php echo $translate('Item set'); ?></h3>
    <div class="metadata">
        <?php echo $itemSet->displayValues(); ?>
    </div>
    <div class="item-set-items">
    <?php echo '<h3>' . $escape($translate('Items')) . '</h3>'; ?>
<?php else: ?>
    <?php echo $this->pageTitle($translate('Items'), 2); ?>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>
<div class="browse-control-mobile">
<button type="button" class="browse-toggle closed"><?php echo $translate('Options'); ?></button>
</div>
<div class="browse-controls closed">
    <?php echo $this->pagination(); ?>
    <?php if (strpos($layoutSetting, 'toggle') !== false): ?>
    <div class="layout-toggle">
        <button type="button" aria-label="<?php echo $translate('Grid'); ?>" class="grid o-icon-grid" <?php echo $gridState; ?>></button>
        <button type="button" aria-label="<?php echo $translate('List'); ?>" class="list o-icon-list" <?php echo $listState; ?>></button>
    </div>
    <?php endif; ?>
    <?php echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?>
    <?php echo $this->sortSelector($sortHeadings); ?>
</div>

<?php $this->trigger('view.browse.before'); ?>
<ul class="resources <?php echo ($isGrid) ? 'resource-grid' : 'resource-list'; ?>">
<?php
foreach ($items as $item):
    $heading = null;
    if ($headingTerm) {
        if (!($heading = $item->value($headingTerm, ['lang' => $lang]))) {
            $heading = $item->value($headingTerm, ['default' => $translate('[Untitled]')]);
        }
    } else {
        $template = $item->resourceTemplate();
        if ($template && $template->titleProperty()) {
            if (($filterLocale == 0) || !($heading = $item->value($template->titleProperty()->term(), ['lang' => $lang]))) {
                $heading = $item->value($template->titleProperty()->term());
            }
        }
    }
    if (!$heading) {
        $heading = $item->displayTitle();
    }

    $body = null;
    if ($bodyTerm) {
        $bodyTermValue = $item->value($bodyTerm);
        $bodyResource = $bodyTermValue ? $bodyTermValue->valueResource() : null;
        $body = ($bodyTermValue && $bodyResource) ? $bodyResource->displayTitle() : $bodyTermValue;
    } else {
        // Based on resource template
        $template = $item->resourceTemplate();
        if ($template && $template->descriptionProperty()) {
            if (($filterLocale == 0) || !($bodyTermValue = $item->value($template->descriptionProperty()->term(), ['lang' => $lang]))) {
                $bodyTermValue = $item->value($template->descriptionProperty()->term());
            }
            if (null !== $bodyTermValue) {
                $bodyResource = $bodyTermValue ? $bodyTermValue->valueResource() : null;
                if ($bodyTermValue && $bodyResource) {
                    if ($headingTerm) {
                        if (! ($body = $bodyResource->value($headingTerm, ['lang' => $lang]))) {
                            $body = $bodyResource->value($headingTerm, ['default' => $translate('[Untitled]')]);
                        }
                    } else {
                        $template = $bodyResource->resourceTemplate();
                        if ($template && $template->titleProperty()) {
                            if (($filterLocale == 0)
                                || ! ($body = $bodyResource->value($template->titleProperty()->term(), ['lang' => $lang]))) {
                                    $body = $bodyResource->value($template->titleProperty()->term());
                                }
                        }
                    }
                    if (!$body) {
                        $body = $bodyResource->displayTitle();
                    }
                } else {
                    $body = $bodyTermValue;
                }
            }
        }
    }
    if (!$body) {
        $body = $item->displayDescription();
    }

?>
    <li class="item resource <?php echo ($isGrid) ? '' : 'media-object'; ?>">
        <?php if ($thumbnail = $this->thumbnail($item, 'medium')): ?>
        <div class="resource-image <?php echo ($isGrid) ? '' : 'media-object-section'; ?>">
            <?php echo $item->linkRaw($thumbnail, null, ['class' => 'thumbnail']); ?>
        </div>
        <?php endif; ?>
        <div class="resource-meta <?php echo ($isGrid) ? '' : 'media-object-section'; ?>">
            <h4><?php echo $item->link($heading); ?></h4>
            <?php if ($body): ?>
            <div class="description <?php echo ($bodyTruncate) ? $bodyTruncate : ''; ?>"><?php echo $escape($body); ?></div>
            <?php endif; ?>
        </div>
    </li>
<?php endforeach; ?>
</ul>
<?php echo ($itemSetShow) ? '</div>' : ''; ?>
<?php $this->trigger('view.browse.after'); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>
