<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$showLayout = $this->themeSetting('show_layout');
$mediaDisplay = $this->themeSetting('media_display');
$galleryDisplay = (isset($mediaDisplay)) ? strpos($mediaDisplay, 'gallery') : false;

if ($galleryDisplay) {
    $sortedMedia = $this->SortMedia($itemMedia);
    $lightMedia = (isset($sortedMedia['lightMedia'])) ? $sortedMedia['lightMedia'] : null;
    $otherMedia = (isset($sortedMedia['otherMedia'])) ? $sortedMedia['otherMedia'] : null;
} else {
    $otherMedia = $itemMedia;
}
?>

<div class="resource-title">
<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
<h3 class="label"><?php echo $translate('Item'); ?></h3>
</div>

<div class="grid-x">
<?php if ($galleryDisplay && isset($lightMedia)): ?>
    <div class="<?php echo $mediaDisplay; ?>">
    <?php echo $this->LightGalleryOutput($lightMedia); ?>
    </div>
<?php elseif((count($itemMedia) > 0) && strpos($mediaDisplay,'double')): ?>
    <div class="<?php echo ($embedMedia) ? 'media-embeds' : 'media-list' ?>">
    <?php foreach ($itemMedia as $media): ?>
        <?php echo ($embedMedia) ? $media->render() : $media->linkPretty(); ?>
    <?php endforeach; ?>
    </div>
<?php endif; ?>

<div id="resource-values" class="<?php echo ($showLayout == 'inline') ? 'inline' : 'stack'; ?>">
    <?php $this->trigger('view.show.before'); ?>
    <?php echo $item->displayValues(); ?>
    <?php $itemSets = $item->itemSets(); ?>
    <?php if (count($itemSets) > 0): ?>
        <dl>
            <div class="property">
                <dt><?php echo $translate('Item sets'); ?></dt>
                <div class="values">
                    <?php foreach ($itemSets as $itemSet): ?>
                        <dd class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></dd>
                   <?php endforeach; ?>
                </div>
            </div>
        </dl>
    <?php endif; ?>
    
    <?php if ($galleryDisplay || $mediaDisplay == 'single'): ?>
        <?php $mediaList = ($galleryDisplay) ? $otherMedia : $itemMedia; ?>
    <?php endif; ?>
    <?php if (isset($mediaList) && count($mediaList) > 0): ?>
        <dl>
            <div class="property">
                <dt><?php echo $translate('Media'); ?></dt>
                <div class="values">
                    <?php foreach ($mediaList as $media): ?>
                        <dd class="value"><?php echo ($embedMedia) ? $media->render() : $media->linkPretty(); ?></dd>
                    <?php endforeach; ?>
            </div>
        </dl>
    <?php endif; ?>
    
    <?php if (($this->siteSetting('show_attached_pages', true)) && ($sitePages = $item->sitePages($site->id()))): ?>
        <dl>
             <div class="property">
                <dt><?php echo $translate('Site pages'); ?></dt>
                <div class="values">
                    <?php foreach ($sitePages as $sitePage): ?>
                        <dd class="value"><?php echo $sitePage->link($sitePage->title()); ?></dd>
                    <?php endforeach; ?>
                </div>
            </div>
        </dl>
    <?php endif; ?>
            
    <?php
        $page = $this->params()->fromQuery('page', 1);
        $property = $this->params()->fromQuery('property');
        $subjectValues = $item->displaySubjectValues($page, 25, $property);
    ?>
    <?php if ($subjectValues): ?>
        <div id="item-linked">
            <h3><?php echo $translate('Linked resources'); ?></h3>
            <?php echo $subjectValues; ?>
        </div>
        <?php endif; ?>
        
        <?php $this->trigger('view.show.after'); ?>
    </div>
    
</div>
