<?php
$translate = $this->plugin('translate');
$showLayout = $this->themeSetting('show_layout');
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
$fullWidthMainBlockContent = $this->resourcePageBlocks($media, 'full_width_main');
$fullWidthMainHasBlocks = $fullWidthMainBlockContent->hasBlocks();
$mainWithSidebarBlockContent = $this->resourcePageBlocks($media);
$mainWithSidebarHasBlocks= $mainWithSidebarBlockContent->hasBlocks();
$leftSidebarBlockContent = $this->resourcePageBlocks($media, 'left');
$leftSidebarHasBlocks = $leftSidebarBlockContent->hasBlocks();
$rightSidebarBlockContent = $this->resourcePageBlocks($media, 'right');
$rightSidebarHasBlocks = $rightSidebarBlockContent->hasBlocks();

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;
?>
<?php $this->htmlElement('body')->appendAttribute('class', 'media resource show'); ?>

<div class="resource-title">
<?php echo $this->pageTitle($media->displayTitle(null, $valueLang), 2); ?>
<h3 class="label"><?php echo $translate('Media'); ?></h3>
</div>
<?php $this->trigger('view.show.before'); ?>
<?php if ($fullWidthMainHasBlocks): ?>
<div class="full-width-main">
    <?php echo $fullWidthMainBlockContent->getBlocks(); ?>
</div>
<?php endif; ?>

<?php if ($mainWithSidebarHasBlocks || $leftSidebarHasBlocks || $rightSidebarHasBlocks): ?>

<?php $sidebarWidth = ($leftSidebarHasBlocks && $rightSidebarHasBlocks) ? '2' : '4'; ?>

<div class="grid-x grid-margin-x">
    <?php if ($leftSidebarHasBlocks): ?>
    <div class="left-sidebar cell medium-<?php echo $sidebarWidth; ?>">
        <?php echo $leftSidebarBlockContent->getBlocks(); ?>
    </div>
    <?php endif; ?>

    <?php if ($mainWithSidebarHasBlocks): ?>
    <div class="main-with-sidebar cell medium-8">
        <?php echo $mainWithSidebarBlockContent->getBlocks(); ?>
    </div>
    <?php endif; ?>

    <?php if ($rightSidebarHasBlocks): ?>
    <div class="right-sidebar cell medium-<?php echo $sidebarWidth; ?>">
        <?php echo $rightSidebarBlockContent->getBlocks(); ?>
    </div>
    <?php endif; ?>
</div>
<?php endif; ?>
<?php $this->trigger('view.show.after'); ?>
