<?php $escape = $this->plugin('escapeHtml'); ?>

<div class="assets">
  <?php foreach ($attachments as $attachment): ?>
    <?php $asset = $attachment['asset']; ?>
    <?php $assetImage = ($asset) ? $this->thumbnail($asset, 'square', ['class' => 'thumbnail']) : ''; ?>
    <div class="asset media-object <?php echo ($assetImage !== '') ? 'has-image' : ''; ?>">
        <?php $page = (array_key_exists('page', $attachment)) ? $attachment['page'] : null; ?>
        <div class="media-object-section">
        <?php if ($page): ?>
            <a href="<?php echo $escape($page->siteUrl()); ?>">
                <?php $altLinkTitle = ($attachment['alt_link_title'] !== '') ? $escape($attachment['alt_link_title']) : false; ?>
                <?php echo $assetImage; ?>
                <span class="link-title"><?php echo ($altLinkTitle) ? $altLinkTitle : $escape($page->title()); ?></span>
            </a>
        <?php else: ?>
            <?php echo $assetImage; ?>
        <?php endif; ?>
        <?php if ($attachment['caption'] !== ''): ?>
        <div class="caption"><?php echo $escape($attachment['caption']); ?></div>
        <?php endif; ?>
        </div>
    </div>
  <?php endforeach; ?>
</div>
