<?php $resourcePageBlocksArray = $this->resourcePageBlocks($resource)->getBlocksArray(); ?>

<ul id="tab-navigation" class="vertical tabs" data-tabs>
<?php $defaultTab = array_key_first($resourcePageBlocksArray); ?>
<?php foreach($resourcePageBlocksArray as $resourcePageBlockName => $resourcePageBlockRender): ?>
    <?php if ($resourcePageBlockRender !== ''): ?>
        <?php $prettyName = ucwords(implode(' ',preg_split('/(?=[A-Z])/', $resourcePageBlockName))); ?>
        <li class="tabs-title <?php echo ($resourcePageBlockName == $defaultTab) ? 'is-active' : ''; ?>"><a href="#tab-<?php echo $resourcePageBlockName; ?>" aria-selected="true"><?php echo ucwords($prettyName); ?></a></li>
    <?php endif; ?>
<?php endforeach; ?>
</ul>